### PR TITLE
#36 robot library first version

### LINKED ISSUE #36: Add Robot scripts code snippets, for usage of Robot lib
Restful API Service Robot scripts:

callAPI.js
```
var lib = require('./libs/helpers');
function main(text, auth){

    /* BASIC GET API call */

    var msg = JSON.parse(text);

    var getUrl = msg.apiGetUrl;
    var getHeaders = {};

    getHeaders['authType'] = 'API';

    print(getUrl);

    var getResponse = lib.get(getUrl, getHeaders);
    print(JSON.stringify(getResponse));
}
```

callBASICAPI.js
```
var lib = require('./libs/helpers');
function main(text, auth){

    /* BASIC GET API call */

    var msg = JSON.parse(text);

    var getUrl = msg.basicGetUrl;
    var getHeaders = {};

    getHeaders['authType'] = 'BASIC';
    getHeaders['username'] = msg.basicUsername;
    getHeaders['password'] = msg.basicPassword;

    print(getUrl);

    var getResponse = lib.get(getUrl, getHeaders);
    print(JSON.stringify(getResponse));
}
```

callOAUTH2API.js
```
var lib = require('./libs/helpers');
function main(text, auth){

    /* OAUTH2 POST API call */

    var msg = JSON.parse(text);

    var postUrl = msg.oauthPostUrl;
    var postHeaders = {};

    postHeaders['authType'] = 'OAUTH2';
    postHeaders['token'] = msg.oauthToken;
    postHeaders['contentType'] = 'application/json';

    var body = '{\"test\":\"data\"}';
    var postResponse = lib.post(postUrl, postHeaders, JSON.parse(body));
    print(JSON.stringify(postResponse));


    /* OAUTH2 GET API call */

    var getUrl = msg.oauthGetUrl;
    var getHeaders = {};

    getHeaders['authType'] = 'OAUTH2';
    getHeaders['token'] = msg.oauthToken;

    var getResponse = lib.get(getUrl, getHeaders);
    print(JSON.stringify(getResponse));

}
```

Notification Services Robot scripts:

logInfoMessage.js
```
var lib = require('./libs/helpers');
function main(text, auth){

    /* lib.say(message to log); */
    lib.say('Hello World');

}
```
sendEmail.js
```
var lib = require('./libs/helpers');
function main(text, auth){

    /* lib.sendEmail(sender's email address,
        recipient's email address,
        subject of your email,
        body of your email);
    */

    var FROM = 'jgaye@microshare.io';
    var TO = 'jgaye@microshare.io';
    var SUBJECT = 'This is a test email';
    var BODY = 'Dear Resident,\n The time we spent together, however long it was, meant the world to me. I would love to see you again but unfortunately I cannot. You see, I am a ghost. I can only materialize once every decade, on the anniversary of my death. I chose to spend my one day among the living with you, sweet resident. Perhaps we will meet again, in another decade--provided you keep your figure.\n Until then, all my love from the beyond,\n Barney.';

    lib.sendEmail(FROM, TO, SUBJECT, BODY);

}
```
sendMicroshareEmail.js
```
var lib = require('./libs/helpers');
function main(text, auth){

    /* lib.sendMicroshareEmail(recipient's email address,
          subject of your email,
          body of your email);
       The email sender will be notification@microshare.io
    */

    var TO = 'jgaye@microshare.io';
    var SUBJECT = 'This is a test email';
    var BODY = 'Dear Resident,\n The time we spent together, however long it was, meant the world to me. I would love to see you again but unfortunately I cannot. You see, I am a ghost. I can only materialize once every decade, on the anniversary of my death. I chose to spend my one day among the living with you, sweet resident. Perhaps we will meet again, in another decade--provided you keep your figure.\n Until then, all my love from the beyond,\n Barney.';

    lib.sendMicroshareEmail(TO, SUBJECT, BODY);

}
```
sendSMS.js
```
var lib = require('./libs/helpers');
function main(text, auth){

    /* lib.sendSMS(sender's phone number (should be your Twilio phone number),
          recipient's phone number,
          content of the SMS,
          your Twilio ACCOUNT_SID,
          your Twilio AUTH_TOKEN);
    */

    var fromPhoneNumber = ???;
    var toPhoneNumber = ???;
    var messageContent = ???;
    var ACCOUNT_SID = ???;
    var AUTH_TOKEN = ???;

    lib.sendSMS(fromPhoneNumber, toPhoneNumber, messageContent, ACCOUNT_SID, AUTH_TOKEN);

}
```
sendWebSocketMessage.js
```
var lib = require('./libs/helpers');
function main(text, auth){

    /* lib.sendWSMessage(WebSocekt service uri, message to send); */

    var wsUri = 'wss://echo.websocket.org';
    var message = 'Hello World';

    lib.sendWSMessage(wsUri, message);

}
```

### PR DESCRIPTION
**Pull request by jgaye**
this closes #36 

Added the Robot library page

Inserted code snippet for the Restful API service and the notification service

### CODE REVIEW

**Comment by tc523** [comment]
LGTM for V1 @jgaye 
I think in the future when we have more to add here, we should consider having these: Restful API service lib, notifications service library, etc as sub headings to be directly viewed and access under Robot Library in the navigation bar instead of everything in a single page. The Modular structure would look good and more comprehensive. This will also let to the addition of these libraries independently by different people without messing/changing other people's work at all.

**Comment by deemcv** [comment]
Hey, grammatically, everything looks good.

**Comment by jgaye** [comment]
Let's merge it.
I do agree with Tamanna that when this grows bigger we need to order it
better. But that's a PR for another day.

**Comment by deemcv** [comment]
Sounds good to me! Would you like the honor of merging it or do you want me
to?

**Pull request merged**
