### PR TITLE
Update demo.md

### PR DESCRIPTION
**Pull request by jimlima**
Per DOC-20 ticket https://microshare.atlassian.net/browse/DOC-20 changed link from pointing to Dev server to pointing to Prod server instead.

### CODE REVIEW

**Review by JulienBardin — CHANGES_REQUESTED** [review]
Change the link on the "demo-live" page too.
I think that the link is potentially different, changing just dapp to app doesn't do the job. Also the app needs to be a guest app.

**Comment by JulienBardin** [comment]
Indeed @jimlima I have tried https://app.microshare.io/guest/5eaaff443d0000e446d39ff0#null and I don't get anything

**Review by tpanagos — APPROVED** [review]
lgtm

**Comment by JulienBardin** [comment]
@jimlima it should be a link to a guest app, but it is not, if you open the link you will not end on the demo dashboard. Probably get in touch with Lisa or Adrien, they might have the link for the demo app.

**Pull request closed without merging**
