### PR TITLE
#173 open shut indicator installation

### PR DESCRIPTION
**Pull request by tidelbo**

### CODE REVIEW

**Review by JulienBardin — CHANGES_REQUESTED** [review]
Your image folder name can't contain some espace. 

you should have /assets/img/Open_Shut_indicator rather than /assets/img/Open Shut indicator     for instance.

Please change that for the images and in the content file

**Review by JulienBardin — COMMENTED** [review]
can you delete the folder of images that we won't use then ?

**Review by simonmicroshare — APPROVED** [review]

**Comment by JulienBardin** [comment]
can you delete the folder of images that we won't use then ?

**Review by simonmicroshare — APPROVED** [review]
The old folder has been deleted

**Pull request merged**
