### PR TITLE
#documentation v3

### PR DESCRIPTION
**Pull request by JulienBardin**
New Design, this is a video of the documentation restyling : 

https://microsharerootoutlook.sharepoint.com/:v:/s/Support/EaZVBxLQgSZFroqHVYA302kB2g68A7Ntt3b6xDR2xnY48w?e=V8z3VR

Dennis, Simon, Rebecca, Lisa saw it, I did some modifications following their opinions, but I think it's now ready for a release.

### CODE REVIEW

**Review by tpanagos — COMMENTED** [review]
@JulienBardin can you describe here what you did with search? That is probably the most risky change in this big PR.

**Comment by JulienBardin** [comment]
Hi @tpanagos, 
Currently the documentation website search bar is using the google search engine. So first of all it’s showing some ads which can bring our customers on some other website, like this example for the word "API" : 
Capture d’écran 2020-11-04 à 18 22 38

Then it scans all the pages of the website, and because our sidebar menu in all the pages hold all the pages names, when you search for "Demo" for exemple some useless links appear. 
Capture d’écran 2020-11-04 à 18 22 22

So I decided to change it for a search bar more simple but efficient. Basically it will just take a look at the different words that you wrote in the search bar and show you the pages that have the word in there name, or these words corresponds to the tags ("keywords") that we can now add into the .ymd file like this (for each pages you can add the right tags) : 
Capture d’écran 2020-11-04 à 18 24 18

So you can search for rectype or demo and it will show you the right pages : 

Capture d’écran 2020-11-04 à 18 23 53
Capture d’écran 2020-11-04 à 18 23 40

**Comment by tpanagos** [comment]
@JulienBardin can you resolve this confliect

**Review by tpanagos — COMMENTED** [review]
Thanks @JulienBardin. If you can resolve the conflict, we can get this merged.

**Pull request merged**
